// File: /types/jgrants.ts

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Note: Some `unknown` types have been manually replaced with more specific types
 * based on the API specification's descriptions and examples.
 */

export interface paths {
  "/subsidies": {
    get: {
      parameters: {
        query: {
          keyword?: string; // Proxyで補うためオプショナル
          sort:
            | "created_date"
            | "acceptance_start_datetime"
            | "acceptance_end_datetime";
          order: "ASC" | "DESC";
          acceptance: "0" | "1";
          use_purpose?: string;
          industry?: string;
          target_number_of_employees?:
            | ""
            | "従業員の制約なし"
            | "5名以下"
            | "20名以下"
            | "50名以下"
            | "100名以下"
            | "300名以下"
            | "900名以下"
            | "901名以上";
          target_area_search?:
            | ""
            | "全国"
            | "北海道地方"
            | "東北地方"
            | "関東・甲信越地方"
            | "東海・北陸地方"
            | "近畿地方"
            | "中国地方"
            | "四国地方"
            | "九州・沖縄地方"
            | "北海道"
            | "青森県"
            | "岩手県"
            | "宮城県"
            | "秋田県"
            | "山形県"
            | "福島県"
            | "茨城県"
            | "栃木県"
            | "群馬県"
            | "埼玉県"
            | "千葉県"
            | "東京都"
            | "神奈川県"
            | "新潟県"
            | "富山県"
            | "石川県"
            | "福井県"
            | "山梨県"
            | "長野県"
            | "岐阜県"
            | "静岡県"
            | "愛知県"
            | "三重県"
            | "滋賀県"
            | "京都府"
            | "大阪府"
            | "兵庫県"
            | "奈良県"
            | "和歌山県"
            | "鳥取県"
            | "島根県"
            | "岡山県"
            | "広島県"
            | "山口県"
            | "徳島県"
            | "香川県"
            | "愛媛県"
            | "高知県"
            | "福岡県"
            | "佐賀県"
            | "長崎県"
            | "熊本県"
            | "大分県"
            | "宮崎県"
            | "鹿児島県"
            | "沖縄県";
          limit?: number;
          offset?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["subsidy-summaries-response"];
          };
        };
      };
    };
  };
  "/subsidies/id/{id}": {
    get: {
      parameters: {
        path: { id: string };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["subsidy-details-response"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 補助金一覧検索結果情報 */
    "subsidy-summaries-response": {
      metadata?: {
        type?: string;
        resultset?: {
          count?: number;
          limit?: number;
          offset?: number;
        };
      };
      result: components["schemas"]["subsidy-summary-item"][];
      message?: string; // エラー時にメッセージが含まれる可能性
    };
    /** @description エラー情報 */
    "500-error-response": {
      type?: string;
      errorCode?: string;
      title?: string;
      instance?: string;
    };
    /** @description 補助金詳細照会結果情報 */
    "subsidy-details-response": {
      metadata?: {
        type?: string;
        resultset?: {
          count?: number;
        };
      };
      result: components["schemas"]["subsidy-detail-item"][];
      message?: string; // エラー時のメッセージ
    };
    /** @description 補助金一覧の各アイテム */
    "subsidy-summary-item": {
      id?: string;
      name?: string; // 補助金番号
      title?: string; // 補助金名
      target_area_search?: string | null;
      acceptance_start_datetime?: string | null;
      acceptance_end_datetime?: string | null;
      target_number_of_employees?: string | null;
      // APIドキュメントにはないが、実際には返ってくるフィールド
      organizer?: string;
      use_purpose?: string;
      industry?: string;
    };
    /** @description 補助金詳細の各アイテム */
    "subsidy-detail-item": {
      id?: string;
      name?: string; // 補助金番号
      title?: string; // 補助金名
      subsidy_catch_phrase?: string | null;
      detail?: string | null; // 補助金のサマリー
      use_purpose?: string | null;
      industry?: string | null;
      target_area_search?: string | null;
      target_area_detail?: string | null;
      target_number_of_employees?: string | null;
      subsidy_rate?: string | null;
      subsidy_max_limit?: number | null;
      acceptance_start_datetime?: string | null;
      acceptance_end_datetime?: string | null;
      project_end_deadline?: string | null;
      request_reception_presence?: "有" | "無" | null;
      is_enable_multiple_request?: boolean | null;
      front_subsidy_detail_page_url?: string | null;
      application_guidelines?: components["schemas"]["file_data"][] | null;
      outline_of_grant?: components["schemas"]["file_data"][] | null;
      application_form?: components["schemas"]["file_data"][] | null;
      // 以下はSwaggerには直接定義されていないが、APIから返ってくる可能性のあるフィールド
      organizer?: string;
      summary?: string;
      description_rich_text?: {
        blocks?: {
          key: string;
          text: string;
          type: string;
          depth: number;
          inlineStyleRanges: unknown[];
          entityRanges: unknown[];
          data: Record<string, unknown>;
        }[];
        entityMap: Record<string, unknown>;
      } | null;
    };
    file_data: {
      name?: string;
      data?: string; // Base64
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
