/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { DocumentDraftRequest, GeneratedSection } from "../models/index";
import {
  DocumentDraftRequestFromJSON,
  DocumentDraftRequestToJSON,
  GeneratedSectionFromJSON,
  GeneratedSectionToJSON,
} from "../models/index";

export interface AiGenerateDocumentDraftPostRequest {
  documentDraftRequest: DocumentDraftRequest;
}

/**
 *
 */
export class AIApi extends runtime.BaseAPI {
  /**
   * Generate AI draft for specified subsidy sections
   */
  async aiGenerateDocumentDraftPostRaw(
    requestParameters: AiGenerateDocumentDraftPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GeneratedSection>>> {
    if (requestParameters["documentDraftRequest"] == null) {
      throw new runtime.RequiredError(
        "documentDraftRequest",
        'Required parameter "documentDraftRequest" was null or undefined when calling aiGenerateDocumentDraftPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/ai/generate-document-draft`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: DocumentDraftRequestToJSON(
          requestParameters["documentDraftRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GeneratedSectionFromJSON),
    );
  }

  /**
   * Generate AI draft for specified subsidy sections
   */
  async aiGenerateDocumentDraftPost(
    requestParameters: AiGenerateDocumentDraftPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GeneratedSection>> {
    const response = await this.aiGenerateDocumentDraftPostRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
