/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationUpdateRequest
 */
export interface ApplicationUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationUpdateRequest
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationUpdateRequest
     */
    progress?: number;
}

/**
 * Check if a given object implements the ApplicationUpdateRequest interface.
 */
export function instanceOfApplicationUpdateRequest(value: object): value is ApplicationUpdateRequest {
    return true;
}

export function ApplicationUpdateRequestFromJSON(json: any): ApplicationUpdateRequest {
    return ApplicationUpdateRequestFromJSONTyped(json, false);
}

export function ApplicationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'progress': json['progress'] == null ? undefined : json['progress'],
    };
}

export function ApplicationUpdateRequestToJSON(json: any): ApplicationUpdateRequest {
    return ApplicationUpdateRequestToJSONTyped(json, false);
}

export function ApplicationUpdateRequestToJSONTyped(value?: ApplicationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'progress': value['progress'],
    };
}

