/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationCreateRequest
 */
export interface ApplicationCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    subsidyName: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    status: ApplicationCreateRequestStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationCreateRequest
     */
    submissionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationCreateRequest
     */
    deadline?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    nextAction?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationCreateRequest
     */
    progress?: number;
}


/**
 * @export
 */
export const ApplicationCreateRequestStatusEnum = {
    1: '準備中',
    2: '審査中',
    3: '採択',
    4: '不採択'
} as const;
export type ApplicationCreateRequestStatusEnum = typeof ApplicationCreateRequestStatusEnum[keyof typeof ApplicationCreateRequestStatusEnum];


/**
 * Check if a given object implements the ApplicationCreateRequest interface.
 */
export function instanceOfApplicationCreateRequest(value: object): value is ApplicationCreateRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('subsidyName' in value) || value['subsidyName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApplicationCreateRequestFromJSON(json: any): ApplicationCreateRequest {
    return ApplicationCreateRequestFromJSONTyped(json, false);
}

export function ApplicationCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'subsidyName': json['subsidyName'],
        'status': json['status'],
        'submissionDate': json['submissionDate'] == null ? undefined : (new Date(json['submissionDate'])),
        'deadline': json['deadline'] == null ? undefined : (new Date(json['deadline'])),
        'nextAction': json['nextAction'] == null ? undefined : json['nextAction'],
        'progress': json['progress'] == null ? undefined : json['progress'],
    };
}

export function ApplicationCreateRequestToJSON(json: any): ApplicationCreateRequest {
    return ApplicationCreateRequestToJSONTyped(json, false);
}

export function ApplicationCreateRequestToJSONTyped(value?: ApplicationCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'subsidyName': value['subsidyName'],
        'status': value['status'],
        'submissionDate': value['submissionDate'] == null ? undefined : ((value['submissionDate'] as any).toISOString().substring(0,10)),
        'deadline': value['deadline'] == null ? undefined : ((value['deadline']).toISOString().substring(0,10)),
        'nextAction': value['nextAction'],
        'progress': value['progress'],
    };
}

