/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyProfile } from "./CompanyProfile";
import {
  CompanyProfileFromJSON,
  CompanyProfileFromJSONTyped,
  CompanyProfileToJSON,
  CompanyProfileToJSONTyped,
} from "./CompanyProfile";

/**
 *
 * @export
 * @interface DocumentDraftRequest
 */
export interface DocumentDraftRequest {
  /**
   *
   * @type {CompanyProfile}
   * @memberof DocumentDraftRequest
   */
  companyInfo: CompanyProfile;
  /**
   *
   * @type {string}
   * @memberof DocumentDraftRequest
   */
  subsidyId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof DocumentDraftRequest
   */
  sections: Array<string>;
}

/**
 * Check if a given object implements the DocumentDraftRequest interface.
 */
export function instanceOfDocumentDraftRequest(
  value: object,
): value is DocumentDraftRequest {
  if (!("companyInfo" in value) || value["companyInfo"] === undefined)
    return false;
  if (!("subsidyId" in value) || value["subsidyId"] === undefined) return false;
  if (!("sections" in value) || value["sections"] === undefined) return false;
  return true;
}

export function DocumentDraftRequestFromJSON(json: any): DocumentDraftRequest {
  return DocumentDraftRequestFromJSONTyped(json, false);
}

export function DocumentDraftRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DocumentDraftRequest {
  if (json == null) {
    return json;
  }
  return {
    companyInfo: CompanyProfileFromJSON(json["companyInfo"]),
    subsidyId: json["subsidyId"],
    sections: json["sections"],
  };
}

export function DocumentDraftRequestToJSON(json: any): DocumentDraftRequest {
  return DocumentDraftRequestToJSONTyped(json, false);
}

export function DocumentDraftRequestToJSONTyped(
  value?: DocumentDraftRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    companyInfo: CompanyProfileToJSON(value["companyInfo"]),
    subsidyId: value["subsidyId"],
    sections: value["sections"],
  };
}
