/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Subsidy
 */
export interface Subsidy {
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  summary?: string;
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  organization?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Subsidy
   */
  categories?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  targetAudience?: string;
  /**
   *
   * @type {Date}
   * @memberof Subsidy
   */
  deadline?: Date;
  /**
   *
   * @type {string}
   * @memberof Subsidy
   */
  amount?: string;
}

/**
 * Check if a given object implements the Subsidy interface.
 */
export function instanceOfSubsidy(value: object): value is Subsidy {
  return true;
}

export function SubsidyFromJSON(json: any): Subsidy {
  return SubsidyFromJSONTyped(json, false);
}

export function SubsidyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Subsidy {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    summary: json["summary"] == null ? undefined : json["summary"],
    organization:
      json["organization"] == null ? undefined : json["organization"],
    categories: json["categories"] == null ? undefined : json["categories"],
    targetAudience:
      json["targetAudience"] == null ? undefined : json["targetAudience"],
    deadline: json["deadline"] == null ? undefined : new Date(json["deadline"]),
    amount: json["amount"] == null ? undefined : json["amount"],
  };
}

export function SubsidyToJSON(json: any): Subsidy {
  return SubsidyToJSONTyped(json, false);
}

export function SubsidyToJSONTyped(
  value?: Subsidy | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    summary: value["summary"],
    organization: value["organization"],
    categories: value["categories"],
    targetAudience: value["targetAudience"],
    deadline:
      value["deadline"] == null
        ? undefined
        : value["deadline"].toISOString().substring(0, 10),
    amount: value["amount"],
  };
}
