/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SubsidyMatch } from "./SubsidyMatch";
import {
  SubsidyMatchFromJSON,
  SubsidyMatchFromJSONTyped,
  SubsidyMatchToJSON,
  SubsidyMatchToJSONTyped,
} from "./SubsidyMatch";

/**
 *
 * @export
 * @interface SubsidySearchResponse
 */
export interface SubsidySearchResponse {
  /**
   *
   * @type {number}
   * @memberof SubsidySearchResponse
   */
  total?: number;
  /**
   *
   * @type {number}
   * @memberof SubsidySearchResponse
   */
  page?: number;
  /**
   *
   * @type {number}
   * @memberof SubsidySearchResponse
   */
  limit?: number;
  /**
   *
   * @type {Array<SubsidyMatch>}
   * @memberof SubsidySearchResponse
   */
  items?: Array<SubsidyMatch>;
}

/**
 * Check if a given object implements the SubsidySearchResponse interface.
 */
export function instanceOfSubsidySearchResponse(
  value: object,
): value is SubsidySearchResponse {
  return true;
}

export function SubsidySearchResponseFromJSON(
  json: any,
): SubsidySearchResponse {
  return SubsidySearchResponseFromJSONTyped(json, false);
}

export function SubsidySearchResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubsidySearchResponse {
  if (json == null) {
    return json;
  }
  return {
    total: json["total"] == null ? undefined : json["total"],
    page: json["page"] == null ? undefined : json["page"],
    limit: json["limit"] == null ? undefined : json["limit"],
    items:
      json["items"] == null
        ? undefined
        : (json["items"] as Array<any>).map(SubsidyMatchFromJSON),
  };
}

export function SubsidySearchResponseToJSON(json: any): SubsidySearchResponse {
  return SubsidySearchResponseToJSONTyped(json, false);
}

export function SubsidySearchResponseToJSONTyped(
  value?: SubsidySearchResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    total: value["total"],
    page: value["page"],
    limit: value["limit"],
    items:
      value["items"] == null
        ? undefined
        : (value["items"] as Array<any>).map(SubsidyMatchToJSON),
  };
}
