/* tslint:disable */
/* eslint-disable */
/**
 * Subsidy Automation API
 * API for the 補助金AI platform. Covers authentication, company profiles, subsidy search & matching, AI‐generated document drafts, application submission, and progress tracking. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubsidyMatch
 */
export interface SubsidyMatch {
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    organization?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubsidyMatch
     */
    categories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    targetAudience?: string;
    /**
     * 
     * @type {Date}
     * @memberof SubsidyMatch
     */
    deadline?: Date;
    /**
     * 
     * @type {string}
     * @memberof SubsidyMatch
     */
    amount?: string;
    /**
     * 
     * @type {number}
     * @memberof SubsidyMatch
     */
    matchScore?: number;
}

/**
 * Check if a given object implements the SubsidyMatch interface.
 */
export function instanceOfSubsidyMatch(value: object): value is SubsidyMatch {
    return true;
}

export function SubsidyMatchFromJSON(json: any): SubsidyMatch {
    return SubsidyMatchFromJSONTyped(json, false);
}

export function SubsidyMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubsidyMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'targetAudience': json['targetAudience'] == null ? undefined : json['targetAudience'],
        'deadline': json['deadline'] == null ? undefined : (new Date(json['deadline'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'matchScore': json['matchScore'] == null ? undefined : json['matchScore'],
    };
}

export function SubsidyMatchToJSON(json: any): SubsidyMatch {
    return SubsidyMatchToJSONTyped(json, false);
}

export function SubsidyMatchToJSONTyped(value?: SubsidyMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'summary': value['summary'],
        'organization': value['organization'],
        'categories': value['categories'],
        'targetAudience': value['targetAudience'],
        'deadline': value['deadline'] == null ? undefined : ((value['deadline']).toISOString().substring(0,10)),
        'amount': value['amount'],
        'matchScore': value['matchScore'],
    };
}

